name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [ opened, labeled, unlabeled, synchronize, reopened, edited ]

jobs:

  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      packages: none
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        # Fivetran build script requires Python 3.10, not above.
        # Testing the destination found that it also requires 3.10, latest does not work.
        python-version: '3.10.8'

    - name: Install Python dependencies
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Install Python connector requirements
      working-directory: examples/connector/python
      run: pip install -r requirements.txt

    - name: Run Python connector build script
      working-directory: examples/connector/python
      run: ./build.sh

    - name: Install Python destination requirements
      working-directory: examples/destination/python
      run: pip install -r requirements.txt

    - name: Run Python destination build script
      working-directory: examples/destination/python
      run: ./build.sh

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        version: "23.2"

    - name: Set up protobuf for Go
      working-directory: examples/connector/golang
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28

    - name: Set up protoc-gen-go
      working-directory: examples/connector/golang
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Set up Go protoc path
      working-directory: examples/connector/golang
      run: export PATH="$PATH:$(go env GOPATH)/bin"

    - name: Verify dependencies
      working-directory: examples/connector/golang
      run: go mod verify

    - name: Build Go connector
      working-directory: examples/connector/golang
      run: scripts/build.sh

    - name: Run go vet
      working-directory: examples/connector/golang
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      working-directory: examples/connector/golang
      run: staticcheck ./...

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      working-directory: examples/connector/golang
      run: golint ./...

    - name: Run tests
      working-directory: examples/connector/golang
      run: go test -race -vet=off ./...

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: Run Java connector copyProtos
      working-directory: examples/connector/java
      run: gradle copyProtos

    - name: Run Java connector test with Gradle Wrapper
      working-directory: examples/connector/java
      run: gradle build

    - name: Run Java destination copyProtos
      working-directory: examples/destination/java
      run: gradle copyProtos

    - name: Run Java destination test with Gradle Wrapper
      working-directory: examples/destination/java
      run: gradle build
